--1 Write a query in SQL to find the name and year of the movies.
--2 Write a query in SQL to find the movies which was released before 1998.
--4 Write a query in SQL to find the name of all reviewers who have rated 7 or more stars to their rating.
--5 Write a query in SQL to find the titles of all movies that have no ratings.
--6 Write a query in SQL to find the titles of the movies with ID 905, 907, 917.
--7 Write a query in SQL to find the list of all those movies with year which include the words Boogie Nights.
--8 Write a query in SQL to find the ID number for the actor whose first name is ‘Woody’ and the last name is ‘Allen’.
--9 Write a query in SQL to list all the information of the actors who played a role in the movie 'Annie Hall'.
--10 Write a query in SQL to list all the movies which released in the country other than UK.
--11 Write a query in SQL to find the movie title, year, date of release, director and actor for those movies which reviewer is unknown.
--12 Write a query in SQL to find the titles of all movies directed by the director whose first and last name are Woddy Allen.
--13 Write a query in SQL to find all the years which produced at least one movie and that received a rating of more than 3 stars. Show the results in increasing order.
--14 Write a query in SQL to find the titles of all movies that have no ratings.
--15 Write a query in SQL to find the names of all reviewers who have ratings with a NULL value.
--16 Write a query in SQL to return the reviewer name, movie title, and stars for those movies which reviewed by a reviewer and must be rated. Sort the result by reviewer name, movie title, and number of stars.
--17 Write a query in SQL to find the reviewer's name and the title of the movie for those reviewers who rated more than one movies.
--18 Write a query in SQL to find the movie title, and the highest number of stars that movie received and arranged the result according to the group of a movie and the movie title appear alphabetically in ascending order.
--19 Write a query in SQL to find the names of all reviewers who rated the movie American Beauty.
--20 Write a query in SQL to find the titles of all movies which have been reviewed by anybody except by Paul Monks.
--21 Write a query in SQL to return the reviewer name, movie title, and number of stars for those movies which rating is the lowest one.
--22 Write a query in SQL to find the titles of all movies directed by James Cameron.
--23 Write a query in SQL to find the name of those movies where one or more actors acted in two or more movies.
--24 Write a query in SQL to list all the movies with title, year, date of release, movie duration, and first and last name of the director which released before 1st January 1989, and sort the result set according to release date from highest date to lowest.
--25 Write a query in SQL to list all the actors who have not acted in any movie between 1990 and 2000.
--26 Write a query in SQL to list the first and last names of all the actors who were cast in the movie 'Annie Hall', and the roles they played in that production.
--27 Write a query in SQL to find the name of all reviewers who have rated their ratings with a NULL value.
--28 Write a query in SQL to find the movie in which the actor appeared whose first and last name are 'Harrison' and 'Ford'.
--29 Write a query in SQL to find the cast list for the movie Chinatown.
--30 Write a query in SQL to find the movie title, actor first and last name, and the role for those movies where one or more actors acted in two or more movies.
--31 Write a query in SQL to find the director's first and last name together with the title of the movie(s) they directed and received the rating.
--32 Write a query in SQL to find movie title and number of stars for each movie that has at least one rating and find the highest number of stars that movie received and sort the result by movie title.
--33 Write a query in SQL to return the reviewer name, movie title, and stars in an order that reviewer name will come first, then by movie title, and lastly by number of stars.
--34 Write a query in SQL to find all the years which produced a movie that received a rating of 3 or 4, and sort the result in increasing order.